### ISSUE TITLE
Implement button svelte components

### ISSUE THREAD

**Issue by benjaminpreiss** [frontline-hq/untitled-ui-components#4]
- [ ] Create new docs page /buttons as a folder in `/routes` (like typography page)
- [ ] Implement svelte component "Button" with the appropriate styles

Make a simple demo of the various styles

**Comment by benjaminpreiss** [comment]
Add component as `Button.svelte` in `/lib` folder

**Comment by benjaminpreiss** [comment]
- [ ] Fix link styles (no borders)
- [ ] Fix tertiary styles (no borders)
- [ ] Verify all styles and spacings

**Comment by JohannaSah** [comment]
blue focus visible border: 
i have removed it, do not know, if that is a good thing, as now it is pretty hard to see where you are when using tabs instead of mouse/trackpad

there is a problem with links, I do not know why the spacing is different in the column after removing the padding as according to the figma styling
